//BUTTONS
export const CLICK_ON_PLUS_BTN='CLICK_ON_PLUS_BTN';
export const CLICK_ON_MINUS_BTN='CLICK_ON_MINUS_BTN';
export const CLICK_ON_RESET_BTN='CLICK_ON_RESET_BTN';
//DROPDOWNS
export const DROPDOWN_SELECTION_HAPPENED='DROPDOWN_SELECTION_HAPPENED';
export const RESET_PARENT_VALUE_SELECTION_TO_NULL='RESET_PARENT_VALUE_SELECTION_TO_NULL';
export const RESET_CHILD_VALUE_SELECTION_TO_NULL='RESET_CHILD_VALUE_SELECTION_TO_NULL';
//PARENT COMPONENT
export const PARENTCOMPONENT_GETCOMPUTEDSTYLE='PARENTCOMPONENT_GETCOMPUTEDSTYLE';
//CHILD COMPONENT - ACTIONBOX
export const ACTIONBOX_WAS_CLICKED='ACTIONBOX_WAS_CLICKED';
export const UPDATE_COMPUTED_VALUE='UPDATE_COMPUTED_VALUE';


// export const GETCOMPUTEDSTYLE_FOR_CHILDCOMPONENT='GETCOMPUTEDSTYLE_FOR_CHILDCOMPONENT';
// export const SELECTED_CATEGORY_PARENT='SELECTED_CATEGORY_PARENT';
// export const SELECTED_VALUE_PARENT='SELECTED_VALUE_PARENT';
// export const SELECTED_CATEGORY_CHILD='SELECTED_CATEGORY_CHILD';
// export const SELECTED_VALUE_CHILD='SELECTED_VALUE_CHILD';
// export const RESET_PARENT_SETTINGS='RESET_PARENT_SETTINGS';
// export const RESET_CLICKED_ACTIONBOX_SETTINGS='RESET_CLICKED_ACTIONBOX_SETTINGS';

